// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRegions() {
  return window['go']['main']['App']['ClearRegions']();
}

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function DefineRegion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DefineRegion'](arg1, arg2, arg3, arg4, arg5);
}

export function DisconnectSerial() {
  return window['go']['main']['App']['DisconnectSerial']();
}

export function GetConnectedPort() {
  return window['go']['main']['App']['GetConnectedPort']();
}

export function SetCaptureRate(arg1) {
  return window['go']['main']['App']['SetCaptureRate'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StartStream() {
  return window['go']['main']['App']['StartStream']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}
