// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRegions():Promise<void>;

export function ConnectSerial(arg1:string):Promise<void>;

export function DefineRegion(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function DisconnectSerial():Promise<void>;

export function GetConnectedPort():Promise<string>;

export function SetCaptureRate(arg1:number):Promise<void>;

export function StartRecording():Promise<string>;

export function StartStream():Promise<void>;

export function StopRecording():Promise<void>;

export function StopStream():Promise<void>;
